# Generated by Django 5.1.7 on 2025-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('ongoing', 'W toku'), ('failed', 'Zakończone niepomyślnie'), ('success', 'Zakończone sukcesem')], default='ongoing', max_length=30),
        ),
    ]
