# Generated by Django 5.1.7 on 2025-04-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_status_type'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
