# Generated by Django 5.1.7 on 2025-04-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_options_offer_description_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('ongoing', 'W toku'), ('failed', 'Zakończone niepomyślnie'), ('success', 'Zakończone sukcesem')], default='ongoing', max_length=7),
        ),
    ]
