# Generated by Django 5.1.7 on 2025-04-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.status'),
        ),
    ]
