# Generated by Django 5.1.7 on 2025-04-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('offers', '0006_alter_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='client_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
