# Generated by Django 5.1.7 on 2025-05-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_remove_offer_products_offerproduct'),
        ('products', '0008_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, through='offers.OfferProduct', to='products.product'),
        ),
    ]
