# Generated by Django 5.1.7 on 2025-04-15 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, default='', max_length=30)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('nip', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('address', models.CharField(blank=True, default='', max_length=120)),
                ('show_created', models.BooleanField(default=True)),
                ('show_client', models.BooleanField(default=True)),
                ('show_client_email', models.BooleanField(default=True)),
                ('show_client_phone', models.BooleanField(default=True)),
                ('show_client_address', models.BooleanField(default=True)),
                ('show_client_region', models.BooleanField(default=True)),
                ('show_status', models.BooleanField(default=True)),
                ('show_description', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
