# Generated by Django 5.1.7 on 2025-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_sort',
            field=models.CharField(blank=True, choices=[('-created', 'Od najnowszych'), ('created', 'Od najstarszych'), ('status', 'Po statusie'), ('description', 'Po opisie'), ('client', 'Po nazwie klienta')], default='', max_length=20),
        ),
    ]
