# Generated by Django 5.1.7 on 2025-04-21 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_usersettings_default_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='default_sort',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='categories_paginator',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='categories_sort',
            field=models.CharField(choices=[('name', 'Nazwa'), ('-name', 'Nazwa od końca'), ('vat', 'Stawka VAT rosnąco'), ('-vat', 'Stawka VAT malejąco')], default='-created', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='offers_paginator',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='offers_sort',
            field=models.CharField(choices=[('-created', 'Od najnowszych'), ('created', 'Od najstarszych'), ('status__name', 'Po statusie'), ('description', 'Po opisie'), ('region', 'Region'), ('client', 'Po nazwie klienta')], default='-created', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='products_sort',
            field=models.CharField(choices=[('serial_number', 'Numer/Kod produktu'), ('-serial_number', 'Numer/Kod produktu odwrócone'), ('name', 'Nazwa'), ('-name', 'Nazwa od końca'), ('category__name', 'Kategorie'), ('-category__name', 'Kategorie odwrócone'), ('purchase_price', 'Cena zakupu malejąco'), ('-purchase_price', 'Cena zakupu rosnąco'), ('sale_price', 'Cena sprzedaży malejąco'), ('-sale_price', 'Cena sprzedaży rosnąco')], default='-created', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='produtcs_paginator',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='statuses_paginator',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='statuses_sort',
            field=models.CharField(choices=[('name', 'Nazwa'), ('-name', 'Nazwa od końca'), ('type', 'Rodzaj'), ('-type', 'Rodzaj od końca')], default='-created', max_length=20),
        ),
    ]
