# Generated by Django 5.1.7 on 2025-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_remove_usersettings_default_sort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='categories_sort',
            field=models.CharField(choices=[('name', 'Nazwa'), ('-name', 'Nazwa od końca'), ('vat', 'Stawka VAT rosnąco'), ('-vat', 'Stawka VAT malejąco')], default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='products_sort',
            field=models.CharField(choices=[('serial_number', 'Numer/Kod produktu'), ('-serial_number', 'Numer/Kod produktu odwrócone'), ('name', 'Nazwa'), ('-name', 'Nazwa od końca'), ('category__name', 'Kategorie'), ('-category__name', 'Kategorie odwrócone'), ('purchase_price', 'Cena zakupu malejąco'), ('-purchase_price', 'Cena zakupu rosnąco'), ('sale_price', 'Cena sprzedaży malejąco'), ('-sale_price', 'Cena sprzedaży rosnąco')], default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='statuses_sort',
            field=models.CharField(choices=[('name', 'Nazwa'), ('-name', 'Nazwa od końca'), ('type', 'Rodzaj'), ('-type', 'Rodzaj od końca')], default='name', max_length=20),
        ),
    ]
