# Generated by Django 5.1.7 on 2025-04-21 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_usersettings_categories_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='clients_paginator',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
