# Generated by Django 5.1.7 on 2025-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_usersettings_clients_paginator'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='company_client_sort',
            field=models.CharField(choices=[('contact_person', 'Osoba do kontaktu'), ('-contact_person', 'Osoba do kontaktu od końca'), ('company_name', 'Nazwa firmy'), ('-company_name', 'Nazwa firmy od końca'), ('email', 'Email'), ('-email', 'Email od końca'), ('address', 'Adres'), ('-address', 'Adres od końca'), ('region', 'Region'), ('-region', 'Region od końca')], default='name', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='individual_client_sort',
            field=models.CharField(choices=[('name', 'Imie'), ('-name', 'Imie od końca'), ('last_name', 'Nazwisko'), ('-last_name', 'Nazwisko od końca'), ('email', 'Email'), ('-email', 'Email od końca'), ('address', 'Adres'), ('-address', 'Adres od końca'), ('region', 'Region'), ('-region', 'Region od końca')], default='name', max_length=20),
        ),
    ]
