# Generated by Django 5.1.7 on 2025-05-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0007_alter_usersettings_company_client_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='categories_sort',
            field=models.CharField(choices=[('name', 'Nazwa'), ('-name', 'Nazwa od końca'), ('-vat', 'Stawka VAT rosnąco'), ('vat', 'Stawka VAT malejąco')], default='name', max_length=20),
        ),
    ]
