# Generated by Django 5.1.7 on 2025-04-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vat',
            field=models.CharField(choices=[('0', '0%'), ('5', '5%'), ('8', '8%'), ('23', '23%')], default='23', max_length=2),
        ),
    ]
