# Generated by Django 5.1.7 on 2025-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_companyclient_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
