# Generated by Django 5.1.7 on 2025-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_companyclient_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='nip',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
