# Generated by Django 5.1.7 on 2025-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_companyclient_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='region',
            field=models.CharField(choices=[('', 'Brak'), ('dol', 'Dolnośląskie'), ('kuj', 'Kujawsko-pomorskie'), ('lube', 'Lubelskie'), ('lubu', 'Lubuskie'), ('lod', 'Łódzkie'), ('mal', 'Małopolskie'), ('maz', 'Mazowieckie'), ('opo', 'Opolskie'), ('podk', 'Podkarpackie'), ('podl', 'Podlaskie'), ('pom', 'Pomorskie'), ('slas', 'Śląskie'), ('swie', 'Świętokrzyskie'), ('war', 'Warmińsko-mazurskie'), ('wie', 'Wielkopolskie'), ('zac', 'Zachodniopomorskie')], default='Brak', max_length=30),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='region',
            field=models.CharField(choices=[('', 'Brak'), ('dol', 'Dolnośląskie'), ('kuj', 'Kujawsko-pomorskie'), ('lube', 'Lubelskie'), ('lubu', 'Lubuskie'), ('lod', 'Łódzkie'), ('mal', 'Małopolskie'), ('maz', 'Mazowieckie'), ('opo', 'Opolskie'), ('podk', 'Podkarpackie'), ('podl', 'Podlaskie'), ('pom', 'Pomorskie'), ('slas', 'Śląskie'), ('swie', 'Świętokrzyskie'), ('war', 'Warmińsko-mazurskie'), ('wie', 'Wielkopolskie'), ('zac', 'Zachodniopomorskie')], default='Brak', max_length=30),
        ),
    ]
